name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install -r dev-requirements.txt
      - name: ruff (linter)
        run: ruff check .
      - name: ruff (formatter)
        run: ruff format --check .
